### ISSUE TITLE
paperswithcode url is broken

### ISSUE THREAD

**Issue by denkorzh** [capjamesg/hugging-face-papers-rss#1]
Hello,
Thank you a lot for your amazing project! I find it very helpful. 

Unfortunately, I noticed the following bug:

https://github.com/capjamesg/hugging-face-papers-rss/blob/6d535462bc549c877a4f230ebc9300d5def29992/app.py#L33

Note that links to arxiv papers are different for HuggingFace papers and PapersWithCode, e.g.
1. https://huggingface.co/papers/2112.09127
2. https://paperswithcode.com/paper/icon-implicit-clothed-humans-obtained-from

So, currently URLs from the feed lead to nowhere.

**Comment by fvillena** [comment]
Same problem here

**Comment by capjamesg** [comment]
This should now be fixed! Let me know if you run into any more issues, or if this issue persists.
